[package]
name = "grars"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.14", features = ["svg", "tokio"] }
thiserror = "2.0"
rodio = "0.19"          # Audio playback
rustfft = "6.2"         # FFT for visualization
dirs = "5.0"            # Config directory paths
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
